# Generated by Django 4.1.5 on 2023-01-22 17:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=35)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('category', models.CharField(max_length=7)),
                ('topic', models.TextField(max_length=400)),
            ],
        ),
    ]
