# Generated by Django 4.1.5 on 2023-01-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=35)),
            ],
        ),
    ]
