# Generated by Django 4.1.5 on 2023-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=7)),
                ('featured_image', models.FileField(upload_to='Image')),
                ('description', models.TextField(max_length=150)),
                ('approved', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
            ],
        ),
    ]
