# Generated by Django 4.1.5 on 2023-01-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
