# Generated by Django 4.1.5 on 2023-01-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0011_remove_post_description_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
